Vagrant.configure("2") do |config|
    config.vm.define :clienteUbuntu do |clienteUbuntu|
        clienteUbuntu.vm.box = "bento/ubuntu-20.04"
        clienteUbuntu.vm.provision :shell, path: "bootstrap_client.sh" 
        clienteUbuntu.vm.network :private_network, ip: "192.168.100.2"
        clienteUbuntu.vm.hostname = "clienteUbuntu"
        
    end
    config.vm.define :servidorUbuntu do |servidorUbuntu|
        servidorUbuntu.vm.box = "bento/ubuntu-20.04"
        servidorUbuntu.vm.provision :shell, path: "bootstrap_server.sh", run: "always"
        servidorUbuntu.vm.network :private_network, ip: "192.168.100.3"
        servidorUbuntu.vm.hostname = "servidorUbuntu"
    end
end