MACHINES = 2

Vagrant.configure("2") do |config|
    config.vm.define :loadBalancer do |loadBalancer|
        loadBalancer.vm.box = "bento/ubuntu-20.04"
        loadBalancer.vm.provision :shell, path: "provision/provision_lxd_cluster_create.sh", :args => ["loadBalancer"]
        loadBalancer.vm.provision :shell, path: "provision/provision_haproxy_lxc.sh", :args => ["loadBalancer", "loadBalancer"]
        loadBalancer.vm.network :private_network, ip: "192.168.100.10"
        loadBalancer.vm.hostname = "loadBalancer"
    end
    (1..MACHINES).each do |i|
        config.vm.define "vagrant#{i}" do |node|
            node.vm.box = "bento/ubuntu-20.04"
            node.vm.provision :shell, path: "provision/provision_lxd_cluster_join.sh", :args => ["vagrant#{i}"]
            node.vm.provision :shell, path: "provision/provision_apache_lxc.sh", :args => ["vagrant#{i}","vagrant#{i}"]
            node.vm.provision :shell, path: "provision/provision_apache_lxc.sh", :args => ["backup#{i}","vagrant#{i}"]
            node.vm.provision :shell, path: "provision/restart_haproxy.sh", :args => ["loadBalancer"]
            node.vm.network :private_network, ip: "192.168.100.1#{i}"
            node.vm.hostname = "vagrant#{i}"
        end
    end
end
