Vagrant.configure("2") do |config|
    config.vm.define :ubuntuServer do |ubuntuServer|
        ubuntuServer.vm.box = "kwilczynski/ubuntu-20.04-docker"
        ubuntuServer.vm.network :private_network, ip: "192.168.100.3"
        ubuntuServer.vm.hostname = "ubuntuServer"
    end
    config.vm.define :restApi do |restApi|
        restApi.vm.hostname = "restApi"
        restApi.vm.network :forwarded_port, guest:5000, host: 5000
        restApi.vm.provider "docker" do |d|
            d.build_dir = "./docker/flask-simple"
        end
    end
end
