Vagrant.configure("2") do |config|
    config.vm.define :ubuntuServer do |ubuntuServer|
        ubuntuServer.vm.box = "kwilczynski/ubuntu-20.04-docker"
        ubuntuServer.vm.network :private_network, ip: "192.168.100.3"
        ubuntuServer.vm.hostname = "ubuntuServer"
    end
end
