version: '2'
services:
   jupyter:      
    image: registry.cn-hangzhou.aliyuncs.com/denverdino/tensorflow:0.9.0      
    ports:           
      - "8888:8888"      
    volumes:        
      - "/tmp/tensorflow_logs"        
      - "./notebooks:/root/notebooks"
    command:        
      - "/run_jupyter.sh"        
      - "/root/notebooks"
   tensorboard:      
    image: registry.cn-hangzhou.aliyuncs.com/denverdino/tensorflow:0.9.0      
    ports:        
      - "6006:6006"      
    volumes_from:        
      - jupyter      
    command:        
      - "tensorboard"        
      - "--logdir"        
      - "/tmp/tensorflow_logs"        
      - "--host"        
      - "0.0.0.0"  
