Vagrant.configure("2") do |config|
    config.vm.define :composeServer do |composeServer|
        composeServer.vm.box = "kwilczynski/ubuntu-20.04-docker"
        composeServer.vm.provision "shell", path: "install_docker_compose.sh"
        composeServer.vm.network :private_network, ip: "192.168.100.3"
        composeServer.vm.hostname = "composeServer"
    end
end
