Vagrant.configure("2") do |config|
    config.vm.define :loadBalancer do |loadBalancer|
        loadBalancer.vm.box = "bento/ubuntu-20.04"
        loadBalancer.vm.provision :shell, path: "provision_haproxy.sh" 
        loadBalancer.vm.network :private_network, ip: "192.168.100.2"
        loadBalancer.vm.hostname = "loadBalancer"
    end
    config.vm.define :vagrant1 do |vagrant1|
        vagrant1.vm.box = "bento/ubuntu-20.04"
        vagrant1.vm.provision "shell", path: "provision_apache.sh"
        vagrant1.vm.network :private_network, ip: "192.168.100.3"
        vagrant1.vm.hostname = "vagrant1"
    end
    config.vm.define :vagrant2 do |vagrant2|
        vagrant2.vm.box = "bento/ubuntu-20.04"
        vagrant2.vm.provision "shell", path: "provision_apache.sh"
        vagrant2.vm.network :private_network, ip: "192.168.100.4"
        vagrant2.vm.hostname = "vagrant2"
    end
    config.vm.define :vagrant3 do |vagrant3|
        vagrant3.vm.box = "bento/ubuntu-20.04"
        vagrant3.vm.provision "shell", path: "provision_apache.sh"
        vagrant3.vm.network :private_network, ip: "192.168.100.5"
        vagrant3.vm.hostname = "vagrant3"
    end
end