config: {}
networks: []
storage_pools: []
profiles: []
cluster:
  server_name: vagrant3
  enabled: true
  member_config:
  - entity: storage-pool
    name: local
    key: source
    value: ""
    description: '"source" property for storage pool "local"'
  cluster_address: 192.168.100.10:8443
  cluster_certificate: |
  server_address: 192.168.100.13:8443
  cluster_password: admin