config: {}
networks: []
storage_pools: []
profiles: []
cluster:
  server_name: vagrant1
  enabled: true
  member_config:
  - entity: storage-pool
    name: local
    key: source
    value: ""
    description: '"source" property for storage pool "local"'
  cluster_address: 192.168.100.10:8443
  cluster_certificate: |
    -----BEGIN CERTIFICATE-----
    MIICFjCCAZugAwIBAgIQNeTlNMmQ1KYKY5FxkPmfHzAKBggqhkjOPQQDAzA6MRww
    GgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRowGAYDVQQDDBFyb290QGxvYWRC
    YWxhbmNlcjAeFw0yMDEwMzAyMzE0MDRaFw0zMDEwMjgyMzE0MDRaMDoxHDAaBgNV
    BAoTE2xpbnV4Y29udGFpbmVycy5vcmcxGjAYBgNVBAMMEXJvb3RAbG9hZEJhbGFu
    Y2VyMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEAo2u8lEvwyhIHGKgoUymBKjHjuPz
    FH6oOoSnu0ds5jeic000c7anp/s3aSjI3618/SSZHg2fgb7sGSALjt4Pe82a4geD
    DnHviADBR4l5WQWaExDoPLRQcK3FKG+8UlvGo2YwZDAOBgNVHQ8BAf8EBAMCBaAw
    EwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAvBgNVHREEKDAmggxs
    b2FkQmFsYW5jZXKHBH8AAAGHEAAAAAAAAAAAAAAAAAAAAAEwCgYIKoZIzj0EAwMD
    aQAwZgIxAMenNXdZIEtEuDn93I84dpHQhgpGsTD+B2FKiQxFvg+GjX/cZNyfohuY
    sHGpyCV1JgIxANx82NRIb3Zl/Ja3itgx144aFKutXxeEEHD9/WU9FJ6YmsdzaVYL
    SuiH9fkD3OrMGA==
    -----END CERTIFICATE-----
  server_address: 192.168.100.11:8443
  cluster_password: admin