apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: image-classifier
  name: image-classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-classifier
  template:
    metadata:
      labels:
        app: image-classifier
    spec: 
      containers:
      - image: omondragon/image-classifier
        name: image-classifier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: node-simple
  name: node-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-simple
  template:
    metadata:
      labels:
        app: node-simple
    spec: 
      containers:
      - image: zestian5/hello-node
        name: node-simple
---
apiVersion: v1
kind: Service
metadata:
  namespace: 
  labels:
    app: node-simple
  name: node-simple
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: node-simple
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  namespace: 
  labels:
    app: image-classifier
  name: image-classifier
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: image-classifier
  type: LoadBalancer