Vagrant.configure("2") do |config|
    config.vm.define :kserver do |kserver|
        kserver.vm.box = "kwilczynski/ubuntu-20.04-docker"
        kserver.vm.network :private_network, ip: "192.168.100.3"
        kserver.vm.hostname = "kserver"
    end
end
